controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1

server:
  replicas: 1
  ingress:
    enabled: ${ argocd_ingress_enabled }
    controller: generic
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-${profile}"
      kubernetes.io/tls-acme: "${ argocd_ingress_tls_acme_enabled }"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "${ argocd_ingress_ssl_passthrough_enabled }"
    ingressClassName: ${ argocd_ingress_class }
    hostname: ${ argocd_server_host }
    tls: true

configs:
    params:
        server.insecure: true
