---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backend-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: auto-ebs-sc
  hostPath:
    path: "/mnt/data"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: auto-ebs-sc
  labels:
    app: db-backend
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
---